version: "3.6"

volumes:
  db:
    driver: local


services:
  minidlna:
    container_name: minidlna
    image: vladgh/minidlna:1.3.0
    network_mode: host
    restart: always
 #   ports:
 #     - 8090:80
 #     - 1900:1900/udp
 #     - 8200:8200/tcp
    volumes:
      - /media/storage/torrents/download:/media/video
      - db:/var/lib/minidlna
    environment:
      - MINIDLNA_FRIENDLY_NAME=MiniDLNA
      - MINIDLNA_MEDIA_DIR_1=/media/video
      - MINIDLNA_ENABLE_TIVO=yes
      - MINIDLNA_INOTIFY=yes
    healthcheck:
      test: ["CMD", "curl", "--silent", "-fail", "localhost:8200"]
      interval: 10s
      timeout: 10s
      retries: 5
