version: '2'

services:
  portainer:
    image: portainer/portainer-ce:linux-amd64-2.17.1
    restart: always
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
